### ISSUE TITLE
Find gtdb files with pattern vs hardcoding exact names

### ISSUE THREAD

**Issue by MrCreosote** [kbase/collections#330]
Context: https://github.com/kbase/collections/pull/329#discussion_r1228747088

Instead of looking for an exact file name, use the pattern `gtdbtk.*.summary.tsv` to find the gtdbtk output files in the tool execution code and the parser. This future proofs us a bit

**Comment by MrCreosote** [comment]
@Xiangs18 this is done isn't it?

**Comment by Xiangs18** [comment]
Hi @MrCreosote, it is merged already!
